project:
  type: website

website:
  title: ""
  page-footer: 
    left: "LVME with EM"
    right: "© 2026"
    border: true
  
  sidebar:
    style: "docked"
    title: "Latent variable models for ecology with EM"
    header: |
      ![](images/HMM.png){width=90%}
    contents:
      - href: index.qmd
        text: Home
      - href: intentions.qmd
        text: Intentions
      - href: authors.qmd
        text: Authors
      - href: tableofcontents.qmd
        text: Organisation
      
      - section: "Codes"
        contents:
          - code_chapter2.qmd
      
  
format:
  html: 
    theme: [cosmo, css/styles.css]
    code-copy: true
    code-line-numbers: false

    
    
 

 
 
    
